[package]
name = "studio-packet-dumper-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"]}

[dependencies.windows]
version = "0.58.0"
features = [
	"Win32"
]